# Generated by Django 4.0.3 on 2022-03-09 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbookhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
