# Generated by Django 4.0.3 on 2022-03-09 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_alter_orderbookhistory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBookSellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxFiled', models.FloatField(blank=True, max_length=1000)),
                ('minFiled', models.FloatField(blank=True, max_length=1000)),
                ('average', models.FloatField(blank=True, max_length=1000)),
                ('total', models.FloatField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
